#!/bin/bash
################################################################################


for var in "$@"
do

	TIME=`date "+%Y\/%m\/%d %H\/%M\/%S"`

	CLASSNAMEN=$var
	TEMPN="$(tr '[:upper:]' '[:lower:]' <<< ${CLASSNAMEN:0})"
	CLASS_NAMEN="$(tr '[:lower:]' '[:upper:]' <<< ${CLASSNAMEN:0})"
	TITLEF="$(tr '[:lower:]' '[:upper:]' <<< ${TEMPN:0:1})${TEMPN:1}"
	SIZEN=`echo ${#TITLEF}`
	NUMN=`expr 80 % ${SIZEN}`
	NUMN=`expr ${NUMN} + 3`
	SPACESN=`seq -f " " ${NUMN} | tr -d '\n'`

	USER=`echo $USER`
	SIZE=`echo ${#USER}`
	NUM=`expr 80 % ${SIZE}`
	SPACES=`seq -f " " ${NUM} | tr -d '\n'`
	CLASSNAME=$var
	TEMP="$(tr '[:upper:]' '[:lower:]' <<< ${CLASSNAME:0})"
	CLASS_NAME="$(tr '[:lower:]' '[:upper:]' <<< ${CLASSNAME:0})"
	TITLE="$(tr '[:lower:]' '[:upper:]' <<< ${TEMP:0:1})${TEMP:1}"
	echo -e "${BGreen}Creating ${CLASSNAME}  ${White}"
	sed -n "2,29p" < ~/.class1/classfile | sed "s/{TIME}/${TIME}$/g" | sed "s/{TITLEF}.hpp/${TITLEF}.hpp${SPACESN}/g" | sed "s/{USERNAME}/${USER}${SPACES}/g" | sed s/{CLASS_NAME}/${CLASS_NAME}/g | sed s/{USERNAME}/${USER}/g | sed s/{TITLE}/${TITLE}/g > ${TITLE}.hpp
	sed -n "31,54p" < ~/.class1/classfile | sed "s/{TIME}/${TIME}$/g" | sed "s/{TITLEF}.cpp/${TITLEF}.cpp${SPACESN}/g" | sed "s/{USERNAME}/${USER}${SPACES}/g" | sed s/{CLASS_NAME}/${CLASS_NAME}/g | sed s/{USERNAME}/${USER}/g | sed s/{TITLE}/${TITLE}/g > ${TITLE}.cpp
	echo "$var"
done
################################################################################
