#!/bin/bash
################################################################################
Reset="\033[0m"       # Text Reset
Black="\033[0;30m"        # Black
Red="\033[0;31m"          # Red
Green="\033[0;32m"        # Green
Yellow="\033[0;33m"       # Yellow
Blue="\033[0;34m"         # Blue
Purple="\033[0;35m"       # Purple
Cyan="\033[0;36m"         # Cyan
White="\033[0;37m"        # White
################################################################################
install() {
	clear
	echo "Are you sure you want install?"
	select yn in "yes" "no"; do
		case $yn in
			yes )
				if cat ~/.zshrc | grep "alias createclass"
				then
					awk '!a[$0]++' ~/.zshrc > temp.txt
					cat ./temp.txt > ~/.zshrc
					rm ./temp.txt
				else
					echo -e "alias createclass='~/.class1/classmaker'" >> ~/.zshrc
				fi
				mkdir -p ~/.class1
				cp ./classfile ~/.class1/.
				cp ./classmaker ~/.class1/.
				chmod +x ~/.class1/classmaker
				echo -e "run the following command:" "${Cyan}" "\n\tsource ~/.zshrc" "${Reset}"
				echo -e "\nTo use the create class run the command:\n\tcreateclass <classname>"
				break;;
			no ) 
				echo -n "aborting...\n";;
		esac
		break;
		echo "${WHITE}"
	done
}
options() {
	clear
	echo -e "${Cyan}"Install"${Reset}" or "${Red}"Remove"${Reset}"?
	echo "type 1 or 2"
	select yn in "install" "remove"; do
		case $yn in
			install )
				install
				break;;
			remove ) 
				rm -rf ~/.class1
				awk '!a[$0]++' ~/.zshrc > temp.txt
				cat ./temp.txt > ~/.zshrc
				NUM=`cat ~/.zshrc | grep -n "alias createclass" | cut -d ":" -f1`
				cat ~/.zshrc | sed "${NUM}d" > temp.txt
				cat ./temp.txt > ~/.zshrc
				rm ./temp.txt;;
		esac
		break;
		echo "${WHITE}"
	done
}
options
